plugins: ['@trivago/prettier-plugin-sort-imports']
printWidth: 120
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
trailingComma: all
bracketSpacing: true
arrowParens: avoid
importOrder: ['<THIRD_PARTY_MODULES>', '^[./]']
importOrderSeparation: true
importOrderSortSpecifiers: true
